name: "Protocol buffer Go stubs generator"
on:
    push:
        tags:
            - v** # workflow is tirggered once a tag (e.g. v1.2.3) is pushed
jobs:
    protoc:
        name: "Generate"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: ["order", "payment", "shipping"] # list of service to be generated
        steps:
            - name: Install GO
              uses: actions/setup-go@v2
              with:
                  go-version: 1.21.1
            - uses: actions/checkout@v2
            - name: Extract Release Version
              run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV
            - name: "generate for golang"
              shell: bash
              run: |
                chmod +x "${GITHUB_WORKSPACE}/run.sh"
                ./run.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }}